### ISSUE TITLE
Godot Download error (in Editor AssetLib)

### ISSUE THREAD

**Issue by cobrapitz** [Leleat/SearchScriptScenePlugin#1]
Godot Version: 3.2.1 rc2
![image](https://user-images.githubusercontent.com/12397702/76059532-6187da80-5f7f-11ea-8307-eb8b34856ab6.png)

PS:
Really looking forward to this addon, I like it!

**Comment by Leleat** [comment]
Looks like the checksum is manually added by a mod (found out via googling). 

I think the error comes because - while the plugin was pending for review - I edited the commit I submitted to the AssetLib (which I probably shouldn't have done). 

I will submit an up-to-date version which should fix this.
(I am fairly new to Godot and and its development, so hopefully )

**Comment by Leleat** [comment]
@cobrapitz Alright, the new submission was approved. I've tested it and the download error no longer happens, so I am gonna close this issue.
